/**
 * TC3-HMAC-SHA256 known-answer test. The expected Authorization below was
 * generated by the OFFICIAL Tencent SDK (`tencentcloud-sdk-nodejs-common`
 * `sign3`) for the same inputs — my signer reproduces it byte-for-byte, and
 * the resulting request was accepted by the ASR auth gateway live
 * (business-level errors follow, never AuthFailure.SignatureFailure).
 *
 * Inputs: SecretId AKIDz8kBbsJjkrqK1V7oO3PAUw9T6F6zyhv, SecretKey
 * Gu5t9xGARNpq86cd98joQYCN3Cozk1qA, timestamp 1551113065, service cvm,
 * payload {"Limit":1}.
 */
import { describe, expect, it } from 'vitest'
import { tc3Sign } from '../src/tencent-asr.ts'

const SECRET_ID = 'AKIDz8kBbsJjkrqK1V7oO3PAUw9T6F6zyhv'
const SECRET_KEY = 'Gu5t9xGARNpq86cd98joQYCN3Cozk1qA'

describe('tc3Sign (Tencent Signature v3)', () => {
  it('reproduces the official SDK authorization for the documented example inputs', () => {
    const signed = tc3Sign({
      method: 'POST',
      uri: '/',
      query: '',
      signedHeaders: {
        'content-type': 'application/json; charset=utf-8',
        host: 'cvm.tencentcloudapi.com',
      },
      body: '{"Limit":1}',
      service: 'cvm',
      secretId: SECRET_ID,
      secretKey: SECRET_KEY,
      timestamp: 1551113065,
    })
    expect(signed.timestamp).toBe(1551113065)
    expect(signed.authorization).toBe(
      'TC3-HMAC-SHA256 Credential=AKIDz8kBbsJjkrqK1V7oO3PAUw9T6F6zyhv/2019-02-25/cvm/tc3_request, '
      + 'SignedHeaders=content-type;host, '
      + 'Signature=d44fdec193ee25cf77b6dbfd767f22f7f44cff2144ec2c57e41f83819fd3fa85',
    )
  })

  it('signs the asr request over content-type and host only (what the ASR gateway accepts)', () => {
    const signed = tc3Sign({
      method: 'POST',
      uri: '/',
      query: '',
      signedHeaders: {
        'content-type': 'application/json; charset=utf-8',
        host: 'asr.tencentcloudapi.com',
      },
      body: '{}',
      service: 'asr',
      secretId: SECRET_ID,
      secretKey: SECRET_KEY,
      timestamp: 1_600_000_000,
    })
    expect(signed.authorization).toContain('/2020-09-13/asr/tc3_request, SignedHeaders=content-type;host')
    expect(signed.authorization).toMatch(/^TC3-HMAC-SHA256 Credential=AKIDz8kBbsJjkrqK1V7oO3PAUw9T6F6zyhv\//)
  })
})
